apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
      - name: user-app-container
        image: 'myapp:1.0'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9191

#  here output 2/2 indicates that there are 2 desired replicas and 2 current replicas of the deployment named user-service-deployment
